# Generated by Django 4.2.20 on 2025-03-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='targer_amount',
            new_name='target_amount',
        ),
    ]
