# Generated by Django 4.2.20 on 2025-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_rename_targer_amount_goal_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='saved_amount',
            field=models.FloatField(default=0),
        ),
    ]
