# Generated by Django 4.2.20 on 2025-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_alter_goal_saved_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='saving_percentage',
            field=models.FloatField(default=10),
        ),
    ]
